GroupLearning/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, re_path
from .views import *
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = 'GroupLearning'

urlpatterns = [
    path('admin/',admin.site.urls),
    path('',LoginForm),
    path('login/',Login),
    path('accounts/login/', Login),
    path('logout_view/', logout_view),
    path('accounts/logout/', logout_view , name='logout'),
    

    path('FirstPageView/', FirstPageView, name='FirstPageView'),
    # path('hr_db_method/', login_required(FirstPageView.hr_db_method), name='hr_db_method'),
    # path('migration/', login_required(FirstPageView.migration), name='migration'),

    # path('PersonnelPaymentView/', login_required(PersonnelPaymentView.as_view()), name='PersonnelPaymentView'),
    # path('get_personnel_data/', login_required(PersonnelPaymentView.get_personnel_data), name='get_personnel_data'),
    # path('SendToKarposhe/', login_required(PersonnelPaymentView.SendToKarposhe), name='SendToKarposhe'),
    path('product_list/', views.ProductList.as_view(), name='product_list'),
    path('view/<int:pk>', views.ProductDetail.as_view(), name='product_view'),
    path('new', views.ProductCreate.as_view(), name='product_new'),
    path('edit/<int:pk>', views.ProductUpdate.as_view(), name='product_edit'),
    path('delete/<int:pk>', views.ProductDelete.as_view(), name='product_delete')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Learning/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GroupLearning.urls'), name='GroupLearning'),
]

GroupLearning/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Name(models.Model):
    col1 = models.CharField(max_length=32)
    col2 = models.IntegerField()
    col3 = models.DateField()

    def __str__(self):
        return col1

    def __unicode__(self):
        return col1

class Product(models.Model):
    name = models.CharField('Name', max_length=100)
    description = models.TextField('Description', blank=True)
    price = models.DecimalField('Price', decimal_places=2, max_digits=8)
    created = models.DateTimeField('Created', auto_now_add=True)
    changed = models.DateTimeField('Changed', auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse('product_edit', kwargs={'pk': self.pk})        

GroupLearning/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import Product

class ProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {
            'class': 'form-control col-md-6'
        }
        self.fields['description'].widget.attrs = {
            'class': 'form-control col-md-6'
        }
        self.fields['price'].widget.attrs = {
            'class': 'form-control col-md-6',
            'step': 'any',
            'min': '1',
        }

    class Meta:
        model = Product
        fields = ('name', 'description', 'price')

GroupLearning/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.views.decorators.csrf import csrf_protect
from django.utils.html import escape
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.db.models import Q
from django.urls import reverse
from django.contrib import auth
from .models import *
from django.views.generic import ListView, DetailView 
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from django.urls import reverse_lazy
from .models import Product
from .forms import ProductForm
# Create your views here.

@csrf_protect
def LoginForm(requset):
    context ={}
    if requset.user.is_authenticated:
        return HttpResponseRedirect('/product_list/')
    else :
        return render(requset,'./templates/CLoginForm.html',context)

@csrf_protect
def Login(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)
    if request.user.is_authenticated:
        return HttpResponseRedirect('/product_list/')
    elif user is not None and user.is_active:
        auth.login(request, user)
        return HttpResponseRedirect('/product_list/')
    else:
        return HttpResponseRedirect('/')



@csrf_protect
def logout_view(requset):
    auth.logout(requset)
    return HttpResponseRedirect("/")

def FirstPageView(requset):
    return render(requset,'./templates/FirstPage.html',{})
class ProductList(ListView): 
    model = Product

class ProductDetail(DetailView): 
    model = Product

class ProductCreate(SuccessMessageMixin, CreateView): 
    model = Product
    form_class = ProductForm
    success_url =reverse_lazy('GroupLearning:product_list')
    success_message = "Product successfully created!"

class ProductUpdate(SuccessMessageMixin, UpdateView): 
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('GroupLearning:product_list')
    success_message = "Product successfully updated!"

class ProductDelete(SuccessMessageMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('GroupLearning:product_list')
    success_message = "Product successfully deleted!"

GroupLearning/templates/GroupLearning/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Conceptu App</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>
  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">Conceptu</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="btn btn-outline-info btn-md" href="{% url 'GroupLearning:product_new' %}">+ New Product</a>
            </li>
            <li class="nav-item">
              <a class="btn btn-outline-info btn-md" href="{% url 'GroupLearning:product_new' %}">+ New Product</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container" id="app">
        {% block content %}
        {% endblock %}
    </div>
    <!-- /.container -->

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

GroupLearning/templates/GroupLearning/product_confirm_delete.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">Delete -
        <small>{{ object }}</small>
    </h1>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-warning" role="alert">
                  Are you sure to delete {{ object }} ?
                </div>
                <input type="submit" class="btn btn-info" value="Yes, delete it" />
                <a class="btn btn-success" href="{% url 'GroupLearning:product_list' %}">No, just I've tried the delete button</a>
            </form>
        </div>
    </div>
{% endblock %}

GroupLearning/templates/GroupLearning/product_detail.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">Detail -
        <small>{{ object.name }}</small>
    </h1>
    <div class="row">
        <div class="col-12">
            <ul class="list-group">
              <li class="list-group-item"><strong>Name:</strong> {{ object.name }}</li>
              <li class="list-group-item"><strong>Description:</strong> {{ object.description }}</li>
              <li class="list-group-item"><strong>Price:</strong> {{ object.price }}</li>
            </ul>
        </div>
    </div>

    <div class="row top-buffer">
        <div class="col-12">
                <a href="{% url 'product_edit' object.id %}"><button type="button" class="btn btn-success">Edit</button></a>
                <a href="{% url 'GroupLearning:product_list' %}"><button type="button" class="btn btn-secondary">Back</button></a>
        </div>
    </div>
{% endblock %}

GroupLearning/templates/GroupLearning/product_form.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">{% if request.path == '/new' %} New Product {% else %} Edit - {% endif %}
        {% if request.path != '/new' %}<small>{{ product.name }}</small>{% endif %}
    </h1>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
                <input type="submit" {% if request.path == '/new' %} value="Add" {% else %} value="Update" {% endif %} class="btn btn-success"/>
                <a href="{% url 'GroupLearning:product_list' %}"><button type="button" class="btn btn-secondary">Back</button></a>
            </form>
        </div>
    </div>
{% endblock %}

GroupLearning/templates/GroupLearning/product_list.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">
        <small>Product List</small>
    </h1>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="row">
    {% if object_list %}
        <div class="col-12" style="overflow-x: scroll">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Price</th>
                    <th scope="col">View</th>
                    <th scope="col">Delete</th>
                </tr>
              </thead>
              <tbody>
                {% for product in object_list %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.description }}</td>
                    <td>{{ product.price }}</td>
                    <td><a href="{% url 'GroupLearning:product_view' product.id %}"><button type="button" class="btn btn-outline-primary btn-sm">View</button></a></td>
                    <td><a href="{% url 'GroupLearning:product_delete' product.id %}"><button type="button" class="btn btn-outline-danger btn-sm">Delete</button></a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
    {% else %}
    <div class="col-12">
        <div class="alert alert-warning" role="alert">
            There is no product, yet. But if you want, you can add from <a class="badge badge-info" href="{% url 'GroupLearning:product_new' %}"><strong>here.</strong></a>
        </div>
    </div>
    {% endif %}
    </div>
{% endblock %}

GroupLearning/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Conceptu App</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>
  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">Conceptu</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="btn btn-outline-info btn-md" href="{% url 'GroupLearning:product_new' %}">+ New Product</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container" id="app">
        {% block content %}
        {% endblock %}
    </div>
    <!-- /.container -->

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

GroupLearning/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Learning</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/Payvast.jfif' %}" width="100%" height="auto" />
</head>

<body>
hello word
<br>
<br>
Abbas
<br>
Ali
<br>
Reza
<br>
Amir
<br>
<br>
<br>
Gooooooooooooo


    <script src="{% static 'js/bootstrap.bundle.min.js' %} " crossorigin="anonymous">
        </script>
    <script src="{% static 'js/myjs.js' %} " crossorigin="anonymous"></script>
    </script>
</body>

</html>

GroupLearning/templates/product_confirm_delete.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">Delete -
        <small>{{ object }}</small>
    </h1>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-warning" role="alert">
                  Are you sure to delete {{ object }} ?
                </div>
                <input type="submit" class="btn btn-info" value="Yes, delete it" />
                <a class="btn btn-success" href="{% url 'GroupLearning:product_list' %}">No, just I've tried the delete button</a>
            </form>
        </div>
    </div>
{% endblock %}

GroupLearning/templates/product_detail.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">Detail -
        <small>{{ object.name }}</small>
    </h1>
    <div class="row">
        <div class="col-12">
            <ul class="list-group">
              <li class="list-group-item"><strong>Name:</strong> {{ object.name }}</li>
              <li class="list-group-item"><strong>Description:</strong> {{ object.description }}</li>
              <li class="list-group-item"><strong>Price:</strong> {{ object.price }}</li>
            </ul>
        </div>
    </div>

    <div class="row top-buffer">
        <div class="col-12">
                <a href="{% url 'product_edit' object.id %}"><button type="button" class="btn btn-success">Edit</button></a>
                <a href="{% url 'GroupLearning:product_list' %}"><button type="button" class="btn btn-secondary">Back</button></a>
        </div>
    </div>
{% endblock %}

GroupLearning/templates/product_form.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">{% if request.path == '/new' %} New Product {% else %} Edit - {% endif %}
        {% if request.path != '/new' %}<small>{{ product.name }}</small>{% endif %}
    </h1>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
                <input type="submit" {% if request.path == '/new' %} value="Add" {% else %} value="Update" {% endif %} class="btn btn-success"/>
                <a href="{% url 'GroupLearning:product_list' %}"><button type="button" class="btn btn-secondary">Back</button></a>
            </form>
        </div>
    </div>
{% endblock %}

GroupLearning/templates/product_list.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">
        <small>Product List</small>
    </h1>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="row">
    {% if object_list %}
        <div class="col-12" style="overflow-x: scroll">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Price</th>
                    <th scope="col">View</th>
                    <th scope="col">Delete</th>
                </tr>
              </thead>
              <tbody>
                {% for product in object_list %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.description }}</td>
                    <td>{{ product.price }}</td>
                    <td><a href="{% url 'GroupLearning:product_view' product.id %}"><button type="button" class="btn btn-outline-primary btn-sm">View</button></a></td>
                    <td><a href="{% url 'GroupLearning:product_delete' product.id %}"><button type="button" class="btn btn-outline-danger btn-sm">Delete</button></a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
    {% else %}
    <div class="col-12">
        <div class="alert alert-warning" role="alert">
            There is no product, yet. But if you want, you can add from <a class="badge badge-info" href="{% url 'GroupLearning:GroupLearning:product_new' %}"><strong>here.</strong></a>
        </div>
    </div>
    {% endif %}
    </div>
{% endblock %}

GroupLearning/templates/products/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Conceptu App</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>
  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">Conceptu</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="btn btn-outline-info btn-md" href="{% url 'GroupLearning:product_new' %}">+ New Product</a>
            </li>
            <li class="nav-item">
              <a class="btn btn-outline-info btn-md" href="{% url 'GroupLearning:logout' %}">- log out</a>
            </li>
            <li class="nav-item">
              <a class="btn btn-outline-info btn-md" href="{% url 'GroupLearning:FirstPageView' %}">karpoushe</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container" id="app">
        {% block content %}
        {% endblock %}
    </div>
    <!-- /.container -->

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

GroupLearning/templates/products/product_confirm_delete.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">Delete -
        <small>{{ object }}</small>
    </h1>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-warning" role="alert">
                  Are you sure to delete {{ object }} ?
                </div>
                <input type="submit" class="btn btn-info" value="Yes, delete it" />
                <a class="btn btn-success" href="{% url 'GroupLearning:product_list' %}">No, just I've tried the delete button</a>
            </form>
        </div>
    </div>
{% endblock %}

GroupLearning/templates/products/product_detail.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">Detail -
        <small>{{ object.name }}</small>
    </h1>
    <div class="row">
        <div class="col-12">
            <ul class="list-group">
              <li class="list-group-item"><strong>Name:</strong> {{ object.name }}</li>
              <li class="list-group-item"><strong>Description:</strong> {{ object.description }}</li>
              <li class="list-group-item"><strong>Price:</strong> {{ object.price }}</li>
            </ul>
        </div>
    </div>

    <div class="row top-buffer">
        <div class="col-12">
                <a href="{% url 'product_edit' object.id %}"><button type="button" class="btn btn-success">Edit</button></a>
                <a href="{% url 'GroupLearning:product_list' %}"><button type="button" class="btn btn-secondary">Back</button></a>
        </div>
    </div>
{% endblock %}

GroupLearning/templates/products/product_form.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">{% if request.path == '/new' %} New Product {% else %} Edit - {% endif %}
        {% if request.path != '/new' %}<small>{{ product.name }}</small>{% endif %}
    </h1>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
                <input type="submit" {% if request.path == '/new' %} value="Add" {% else %} value="Update" {% endif %} class="btn btn-success"/>
                <a href="{% url 'GroupLearning:product_list' %}"><button type="button" class="btn btn-secondary">Back</button></a>
            </form>
        </div>
    </div>
{% endblock %}

GroupLearning/templates/products/product_list.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">
        <small>Product List</small>
    </h1>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="row">
    {% if object_list %}
        <div class="col-12" style="overflow-x: scroll">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Price</th>
                    <th scope="col">View</th>
                    <th scope="col">Delete</th>
                </tr>
              </thead>
              <tbody>
                {% for product in object_list %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.description }}</td>
                    <td>{{ product.price }}</td>
                    <td><a href="{% url 'GroupLearning:product_view' product.id %}"><button type="button" class="btn btn-outline-primary btn-sm">View</button></a></td>
                    <td><a href="{% url 'GroupLearning:product_delete' product.id %}"><button type="button" class="btn btn-outline-danger btn-sm">Delete</button></a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
    {% else %}
    <div class="col-12">
        <div class="alert alert-warning" role="alert">
            There is no product, yet. But if you want, you can add from <a class="badge badge-info" href="{% url 'GroupLearning:product_new' %}"><strong>here.</strong></a>
        </div>
    </div>
    {% endif %}
    </div>
{% endblock %}

templates/FirstPage.html
{% extends "./base.html" %}



{% load static %}

{% block content %}

<script>
    $(document).ready(function () {


        $(".datepicker").persianDatepicker({
            theme: "latoja",
            formatDate: "YYYY/0M/0D",
            cellWidth: 40,
            cellHeight: 25,
            shortDowTitle: ["ش", "ی", "د", "س", "چ", "پ", "ج"],
            fontSize: 12
        });


    });
</script>

<h1 class="text-center font-weight-bold">ارسال فیش حقوقی به سیستم کارپوشه ملی ایران</h1>

Hello World


{% endblock %}

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Conceptu App</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>
  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">Conceptu</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="btn btn-outline-info btn-md" href="{% url 'GroupLearning:product_new' %}">+ New Product</a>
              
            </li>
          
          </ul>
        </div>
        
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container" id="app">
        {% block content %}
        {% endblock %}
    </div>
    <!-- /.container -->

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/product_confirm_delete.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">Delete -
        <small>{{ object }}</small>
    </h1>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-warning" role="alert">
                  Are you sure to delete {{ object }} ?
                </div>
                <input type="submit" class="btn btn-info" value="Yes, delete it" />
                <a class="btn btn-success" href="{% url 'GroupLearning:product_list' %}">No, just I've tried the delete button</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/product_list.html
{% extends 'products/base.html' %}

{% block content %}
    <h1 class="my-4">
        <small>Product List</small>
    </h1>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="row">
    {% if object_list %}
        <div class="col-12" style="overflow-x: scroll">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Price</th>
                    <th scope="col">View</th>
                    <th scope="col">Delete</th>
                </tr>
              </thead>
              <tbody>
                {% for product in object_list %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.description }}</td>
                    <td>{{ product.price }}</td>
                    <td><a href="{% url 'GroupLearning:product_view' product.id %}"><button type="button" class="btn btn-outline-primary btn-sm">View</button></a></td>
                    <td><a href="{% url 'GroupLearning:product_delete' product.id %}"><button type="button" class="btn btn-outline-danger btn-sm">Delete</button></a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
    {% else %}
    <div class="col-12">
        <div class="alert alert-warning" role="alert">
            There is no product, yet. But if you want, you can add from <a class="badge badge-info" href="{% url 'GroupLearning:product_new' %}"><strong>here.</strong></a>
        </div>
    </div>
    {% endif %}
    </div>
{% endblock %}